### ISSUE TITLE
Unified Styles

### ISSUE THREAD

**Issue by justinpombrio** [justinpombrio/partial-pretty-printer#16]
Merge "marks" and "styles", into a single thing called "styles".

- `trait Style: Debug + Clone + Default { fn combine(parent: Style, child: Style) -> Style }`
- Type param `StyleLabel`
- Type param `Style` implements `trait Style`
- `Notation::Style(StyleLabel, Notation)`
- `PrettyDoc.node_style(self) -> Style`
- PrettyDoc.lookup_style(self, StyleLabel) -> Style`

All handled in `ConsolidatedNotation`.

Checklist:

- [ ] Search for "[Mm]ark"

**Comment by justinpombrio** [comment]
Add a `StyleLabel` field to `Notation::Indent` so that you can style just the indentation. Not needed for `Literal` or `Text`.

**Comment by e-matteson** [comment]
Done in PR #17.
